/* eslint-disable no-unused-vars */
import React from 'react';
import Navbar from '../Components/navbar';
import Footer from '../Components/footer';

const TermsAndConditions = () => {
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return (
    <>
      <Navbar />
      
      <main className="max-w-6xl mx-auto px-5 py-12 mt-20">
        {/* Header Section */}
        <section className="mb-12 text-center">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            Terms and Conditions
          </h1>
          <p className="text-lg text-gray-600">
            Last Updated: {currentDate}
          </p>
        </section>

        {/* Introduction */}
        <div className="bg-blue-50 p-6 rounded-lg mb-12">
          <p className="text-gray-700">
            Please read these Terms and Conditions carefully before using our services. By accessing or using our platform, 
            you agree to be bound by these terms and all applicable laws and regulations of Bangladesh.
          </p>
        </div>

        {/* Terms Content */}
        <div className="space-y-12">
          {/* New Section: Acceptance of Terms */}
          <section>
            <h2 className="text-2xl font-bold text-gray-800 mb-4 flex items-center">
              <span className="bg-blue-600 text-white rounded-full w-8 h-8 flex items-center justify-center mr-3">1</span>
              Acceptance of Terms
            </h2>
            <div className="ml-11 space-y-4">
              <p>
                <strong>1.1</strong> By accessing and using this website , you accept and agree to be bound by these Terms and Conditions. 
                If you do not agree with any part of these terms, you must not use our Service.
              </p>
              <p>
                <strong>1.2</strong> These Terms constitute a legally binding agreement between you and Cross Careers regarding your use of the Service.
              </p>
            </div>
          </section>

          {/* Section 2 (renumbered) */}
          <section>
            <h2 className="text-2xl font-bold text-gray-800 mb-4 flex items-center">
              <span className="bg-blue-600 text-white rounded-full w-8 h-8 flex items-center justify-center mr-3">2</span>
              Definitions & Interpretation
            </h2>
            <div className="ml-11 space-y-4">
              <p>
                <strong>2.1 </strong> refers to the website, its subdomains, and all features (job listings, resume tools, etc.).
              </p>
              <p>
                <strong>2.2 </strong> means any individual or entity accessing the Service.
              </p>
              <p>
                <strong>2.3 </strong> includes text, data, graphics, and materials generated by Users or the Company.
              </p>
              <p>
                <strong>2.4 </strong> refers to the ICT Act 2006 (as amended), Digital Security Act 2018, 
                Contract Act 1872, and Consumer Rights Protection Act 2009.
              </p>
              <p className="italic text-gray-600">
                Interpretation: Terms shall be construed under Bangladeshi legal principles. Gender-neutral language applies.
              </p>
            </div>
          </section>

          {/* Section 3 (renumbered) */}
          <section>
            <h2 className="text-2xl font-bold text-gray-800 mb-4 flex items-center">
              <span className="bg-blue-600 text-white rounded-full w-8 h-8 flex items-center justify-center mr-3">3</span>
              Binding Agreement
            </h2>
            <div className="ml-11 space-y-4">
              <p>
                <strong>3.1</strong> By using the Service, Users irrevocably agree to these Terms. If the User is a corporate entity, 
                the signatory warrants authority to bind the entity.
              </p>
              <p>
                <strong>3.2</strong> Minors (under 18 years) cannot use the Service without parental consent (per Bangladesh Majority Act 1875).
              </p>
            </div>
          </section>

          {/* Section 4 (renumbered) */}
          <section>
            <h2 className="text-2xl font-bold text-gray-800 mb-4 flex items-center">
              <span className="bg-blue-600 text-white rounded-full w-8 h-8 flex items-center justify-center mr-3">4</span>
              User Obligations & Prohibited Conduct
            </h2>
            <div className="ml-11 space-y-4">
              <p><strong>Users must not:</strong></p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Post false, defamatory, or unlawful content (Digital Security Act 2018, Sections 21-29)</li>
                <li>Use the Service for fraud, phishing, or financial scams (Penal Code 1860, Sections 415-420)</li>
                <li>Reverse-engineer or disrupt the Service (Copyright Act 2000, Section 72)</li>
                <li>Violate third-party intellectual property rights</li>
              </ul>
              <p className="font-semibold">
                Consequences: Violations may lead to account termination, legal action, and reporting to Bangladesh Cyber Tribunal.
              </p>
            </div>
          </section>

          {/* Section 5 (renumbered) */}
          <section>
            <h2 className="text-2xl font-bold text-gray-800 mb-4 flex items-center">
              <span className="bg-blue-600 text-white rounded-full w-8 h-8 flex items-center justify-center mr-3">5</span>
              Account Security & Liability
            </h2>
            <div className="ml-11 space-y-4">
              <p>
                <strong>5.1</strong> Users are solely liable for account breaches due to negligence (ICT Act 2006, Section 17).
              </p>
              <p>
                <strong>5.2</strong> The Company reserves the right to suspend accounts suspected of fraudulent activity.
              </p>
            </div>
          </section>

          {/* Section 6 (renumbered) */}
          <section>
            <h2 className="text-2xl font-bold text-gray-800 mb-4 flex items-center">
              <span className="bg-blue-600 text-white rounded-full w-8 h-8 flex items-center justify-center mr-3">6</span>
              Intellectual Property Rights
            </h2>
            <div className="ml-11 space-y-4">
              <p>
                <strong>6.1</strong> All trademarks, logos, and software are owned by the Company (Copyright Act 2000, Sections 15-16).
              </p>
              <p>
                <strong>6.2</strong> User-generated content grants the Company a non-exclusive, royalty-free license to display and distribute it.
              </p>
            </div>
          </section>

          {/* Section 7 (renumbered) */}
          <section>
            <h2 className="text-2xl font-bold text-gray-800 mb-4 flex items-center">
              <span className="bg-blue-600 text-white rounded-full w-8 h-8 flex items-center justify-center mr-3">7</span>
              Disclaimers & Limitation of Liability
            </h2>
            <div className="ml-11 space-y-4">
              <p>
                <strong>7.1 No Warranty:</strong> The Service is provided  without guarantees of accuracy or uptime.
              </p>
              <p>
                <strong>7.2 Third-Party Links:</strong> The Company disclaims liability for external sites (Consumer Rights Protection Act 2009, Section 45).
              </p>
              <p>
                <strong>7.3 Maximum Liability:</strong> The  liability is capped at BDT 10,000 (per Contract Act 1872, Section 74).
              </p>
            </div>
          </section>

          {/* Section 8 (renumbered) */}
          <section>
            <h2 className="text-2xl font-bold text-gray-800 mb-4 flex items-center">
              <span className="bg-blue-600 text-white rounded-full w-8 h-8 flex items-center justify-center mr-3">8</span>
              Data Privacy & Compliance
            </h2>
            <div className="ml-11 space-y-4">
              <p>
                <strong>8.1</strong> Personal data is processed per the Digital Security Act 2018 and proposed Data Protection Act.
              </p>
              <p>
                <strong>8.2</strong> Users consent to data collection for service improvement and legal compliance.
              </p>
            </div>
          </section>

          {/* Section 9-15 (renumbered) */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {[
              {
                number: '9',
                title: 'Termination',
                content: [
                  '9.1 The Company may terminate access without notice for violations.',
                  '9.2 Users may request account deletion, subject to Bangladesh\'s data retention laws.'
                ]
              },
              {
                number: '10',
                title: 'Dispute Resolution & Governing Law',
                content: [
                  '10.1 Jurisdiction: Disputes shall be resolved in Dhaka District Courts.',
                  '10.2 Arbitration: Parties agree to mediate before litigation (Arbitration Act 2001).',
                  '10.3 Governing Law: These Terms are governed by Bangladeshi law.'
                ]
              },
              {
                number: '11',
                title: 'Amendments',
                content: [
                  '11.1 The Company may modify these Terms with 30 days\' notice.',
                  '11.2 Continued use constitutes acceptance of changes.'
                ]
              },
              {
                number: '12',
                title: 'Fraud & Financial Scam Disclaimer',
                content: [
                  '12.1 The Company does not charge fees for job applications.',
                  '12.2 Users are warned against sharing bank details or paying for job offers (Penal Code 1860, Section 420).',
                  '12.3 Report scams to Bangladesh Cyber Crime Investigation Unit.'
                ]
              },
              {
                number: '13',
                title: 'Force Majeure',
                content: [
                  'The Company is not liable for delays caused by:',
                  '- Cyberattacks (Digital Security Act 2018)',
                  '- Government restrictions',
                  '- Natural disasters'
                ]
              },
              {
                number: '14',
                title: 'Severability',
                content: [
                  'If any clause is deemed invalid, the remainder of the Terms remains enforceable (Contract Act 1872, Section 23).'
                ]
              }
            ].map((section) => (
              <section key={section.number} className="bg-white p-6 rounded-lg shadow-xs border border-gray-100">
                <h2 className="text-xl font-bold text-gray-800 mb-3 flex items-center">
                  <span className="bg-blue-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm mr-2">
                    {section.number}
                  </span>
                  {section.title}
                </h2>
                <div className="ml-8 space-y-2">
                  {section.content.map((item, index) => (
                    <p key={index} className="text-gray-700">{item}</p>
                  ))}
                </div>
              </section>
            ))}
          </div>

          {/* Section 15 (renumbered) */}
          <section className="bg-blue-50 p-6 rounded-lg">
            <h2 className="text-2xl font-bold text-gray-800 mb-4">15. Contact & Legal Notices</h2>
            <p className="text-gray-700 mb-2">
              All legal notices must be sent to:
            </p>
            <address className="not-italic">
              <p className="font-semibold">Cross Careers</p>
              <p>[32/2, BBCS lane, senpara parbota, Mirpur -10]</p>
              <p>Dhaka, Bangladesh</p>
              <p>Email: <a href="mailto:ed.youthindevelopment@gmail.com" className="text-blue-600">ceo.crosscareers@gmail.com</a></p>
            </address>
          </section>
        </div>
      </main>
      
      <Footer />
    </>
  );
};

export default TermsAndConditions;